stages:
    - build
    # - test
    # - deploy

build:
    stage: build
    image: docker
    tags:
        - nei-runner

    services:
        - docker:dind

    script:
        - echo "hello world"
        - ls -al
        - docker pull nginx
        - docker images
    # script:
    #     - docker build -t $DOCKER_REGISTRY/$DOCKER_REPO:$CI_COMMIT_TAG
    #     - docker tag app06:latest $DOCKER_REGISTRY/$DOCKER_REPO:$CI_COMMIT_TAG
    #     - aws ecr get-login-password --region eu-west-1 --profile 8027 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    #     - docker push $DOCKER_REGISTRY/$DOCKER_REPO:$CI_COMMIT_TAG
# deploy:
#     stage: deploy
#     image: 802783396857.dkr.ecr.eu-west-1.amazonaws.com/nei_repository:latest
#     script:
#         - docker build -t $CI

# cache:
#   paths:
#     - node_modules/

# test_async:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/async.spec.js

# test_db:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/db-postgres.spec.js

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
