stages:
    - build
    # - test
    # - deploy

build:
    stage: build
    image: node:latest
    tags:
        - nei-runner

    # services:
    #     - docker:20.10.16-dind

    # script:
    #     - echo "hello world"
    #     - ls -al
    #     - docker pull nginx
    #     - docker images
    script:
        # - docker buildx build --platform linux/amd64 -t $DOCKER_REGISTRY/$DOCKER_REPO:$CI_COMMIT_TAG .
        - /usr/bin/docker build -t $DOCKER_REGISTRY:$CI_PIPELINE_IID .
        - /usr/bin/docker tag $DOCKER_REGISTRY:$CI_PIPELINE_IID $DOCKER_REGISTRY:latest
        - /usr/bin/docker images
    #     - aws ecr get-login-password --region eu-west-1 --profile 8027 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    #     - docker push $DOCKER_REGISTRY/$DOCKER_REPO:$CI_COMMIT_TAG
# deploy:
#     stage: deploy
#     image: 802783396857.dkr.ecr.eu-west-1.amazonaws.com/nei_repository:latest
#     script:
#         - docker build -t $CI

# cache:
#   paths:
#     - node_modules/

# test_async:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/async.spec.js

# test_db:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/db-postgres.spec.js

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
